### ISSUE TITLE
[$100] Remove All Users Button

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/topcoder-x-ui#284] opened 2020-01-31 16:45 UTC
On the `Git access control` page, add a button that will remove all users added to the repository by TCX, for a given team.

**NOTE:**
This will require new tracking functionality to the Git Access Control flow that adds a record to a new DynamoDB table to track users added through TC-X.

**Comment by jmgasper** [comment] 2020-03-25 06:11
@afrisalyp - We added the button, but I don't see it working in my tests for Gitlab.  Can you test as well please?

**Comment by jmgasper** [comment] 2020-03-25 06:12
Contest https://www.topcoder.com/challenges/30120850 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2020-03-25 06:13
Contest https://www.topcoder.com/challenges/30120850 has been updated - it has been assigned to afrisalyp.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by afrisalyp** [comment] 2020-03-26 01:16
@jmgasper 

I've tested the feature and these are my findings:

1. The feature works on both Gitlab and Github for newly added users. You can see the screencast here: 
Github: https://drive.google.com/open?id=1JsXQxLH-BDrvVpYF4MCnsiE91ODAPYvP
Gitlab: https://drive.google.com/open?id=1Iag5XSQlpnZmrJ4mBGp6RtZlvH2P3-v1

2. For users that added before the new feature is deployed, the feature can not delete them. Screencast: https://drive.google.com/open?id=1qUZSmEqFaGURA4kl7pAVpAt0YkVAnIRD

It might be that the problem is predicted since the new feature will record added users on the DB. So if we want to remove all users, the old added users won't be affected.

3. I see error logs when starting topcoder-x-ui. The error might be related to the new feature since the DB model is updated.

```
error: Error happened in system
Error: Topcoder_X.OwnerUserGroup indexes are not synchronized and update flag is set to false
    at /home/afrisalyp/topcoder/topcoder-x/topcoder-x-ui/node_modules/dynamoose/lib/Table.js:177:27
    at _fulfilled (/home/afrisalyp/topcoder/topcoder-x/topcoder-x-ui/node_modules/q/q.js:854:54)
    at /home/afrisalyp/topcoder/topcoder-x/topcoder-x-ui/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/home/afrisalyp/topcoder/topcoder-x/topcoder-x-ui/node_modules/q/q.js:816:13)
    at /home/afrisalyp/topcoder/topcoder-x/topcoder-x-ui/node_modules/q/q.js:624:44
    at runSingle (/home/afrisalyp/topcoder/topcoder-x/topcoder-x-ui/node_modules/q/q.js:137:13)
    at flush (/home/afrisalyp/topcoder/topcoder-x/topcoder-x-ui/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
error: Error happened in system
Error: Topcoder_X.OwnerUserTeam indexes are not synchronized and update flag is set to false
    at /home/afrisalyp/topcoder/topcoder-x/topcoder-x-ui/node_modules/dynamoose/lib/Table.js:177:27
    at _fulfilled (/home/afrisalyp/topcoder/topcoder-x/topcoder-x-ui/node_modules/q/q.js:854:54)
    at /home/afrisalyp/topcoder/topcoder-x/topcoder-x-ui/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/home/afrisalyp/topcoder/topcoder-x/topcoder-x-ui/node_modules/q/q.js:816:13)
    at /home/afrisalyp/topcoder/topcoder-x/topcoder-x-ui/node_modules/q/q.js:624:44
    at runSingle (/home/afrisalyp/topcoder/topcoder-x/topcoder-x-ui/node_modules/q/q.js:137:13)
    at Timeout.flush [as _onTimeout] (/home/afrisalyp/topcoder/topcoder-x/topcoder-x-ui/node_modules/q/q.js:125:13)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

Please let me know if you have any thoughts on this.

**Closed** 2020-03-26 01:24 UTC
Labels: tcx_Assigned, tcx_FixAccepted

**Comment by jmgasper** [comment] 2020-03-26 01:25
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30120850<br/><br/>```This is an automated message for ghostar via Topcoder X```
