### ISSUE TITLE
[$50] Failing to pay ticket

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#245] opened 2019-11-23 06:42 UTC
@afrisalyp - Another one that's failing is a ticket in a private repo.

The DB has this repo ID, challenge ID, number, and provider, but it seems to be failing to find the ticket:

```
debug: Enter ensureChallengeExists to scan an issue record
debug: Enter ensureChallengeExists. Number: 39
debug: Enter ensureChallengeExists. provider: github
debug: Enter ensureChallengeExists. repositoryId: 221569487
debug: Enter scanOne.
debug: scanOne. Error. TypeError: Cannot read property 'map' of undefined
debug: scanOne. Result.
debug:
error: Error happened in system
TypeError: Cannot read property 'count' of undefined
    at model.scan.exec (/topcoder-x-processor/utils/db-helper.js:67:29)
    at /topcoder-x-processor/node_modules/q/q.js:2059:17
    at runSingle (/topcoder-x-processor/node_modules/q/q.js:137:13)
    at flush (/topcoder-x-processor/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
error: Error happened in process
TypeError: Cannot read property 'id' of undefined
    at handleIssueClose (/topcoder-x-processor/services/IssueService.js:482:51)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:122:5)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at Immediate._tickDomainCallback (internal/process/next_tick.js:219:9)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
error:  message=Cannot read property 'id' of undefined, stack=TypeError: Cannot read property 'id' of undefined
    at handleIssueClose (/topcoder-x-processor/services/IssueService.js:482:51)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:122:5)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at Immediate._tickDomainCallback (internal/process/next_tick.js:219:9)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5), logged=true
debug:
error: Error happened in system
```

**Comment by jmgasper** [comment] 2019-11-23 06:46
Contest https://www.topcoder.com/challenges/30107828 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2019-11-23 06:46
Contest https://www.topcoder.com/challenges/30107828 has been updated - it has been assigned to afrisalyp.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by afrisalyp** [comment] 2019-11-23 10:00
Accidentally close this. Sorry. :D

**Comment by jmgasper** [comment] 2019-11-23 10:02
Payment failed: [400]: Failed to update challenge. Detail: javax.ejb.EJBTransactionRolledbackException<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by afrisalyp** [comment] 2019-11-23 10:10
I can't reproduce this issue.
But upgrading dynamoose is a possible solution.
https://github.com/dynamoosejs/dynamoose/issues/248

Also, there are some missed `return` in `reject` code.

**Comment by afrisalyp** [comment] 2019-11-23 10:11
`package.json` is updated. 
So please clean the `node-module` and `package-lock.json` when deploying it to prod.
Thanks.

**Comment by jmgasper** [comment] 2019-11-23 10:39
Payment failed: [400]: Failed to update challenge. Detail: javax.ejb.EJBTransactionRolledbackException<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2019-11-23 21:01
@afrisalyp - The cleaning of node modules is done on every deploy.

**Comment by jmgasper** [comment] 2019-11-24 04:00
@afrisalyp - Testing this out, and the response data isn't getting properly logged:

```
error: Response Data: [object Object]
```

**Comment by afrisalyp** [comment] 2019-11-24 04:13
@jmgasper - log fixed.

**Comment by jmgasper** [comment] 2019-11-24 07:34
@afrisalyp - That's great, thanks!  I've been able to capture what's happening and I've reported it to the team that handles the challenge API.  Something's weird and it's only in prod, for some reason.  It's throwing an odd SQLException in the challenge API.  Hopefully they can fix it ASAP.

**Comment by afrisalyp** [comment] 2019-11-24 08:35
Sounds good. Hope it'll be fixed soon.
Thanks.

**Comment by jmgasper** [comment] 2019-11-28 03:33
Contest https://www.topcoder.com/challenges/30108384 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment] 2019-11-28 03:34
Contest https://www.topcoder.com/challenges/30108384 has been updated - it has been assigned to afrisalyp.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Closed** 2019-11-28 06:39 UTC
Labels: tcx_Assigned, tcx_FixAccepted

**Comment by jmgasper** [comment] 2019-11-28 06:40
Payment task has been updated: https://software.topcoder-dev.com/review/actions/ViewProjectDetails?pid=30108384<br/><br/>```This is an automated message for ghostar via Topcoder X```
